# Generated by Django 5.1.7 on 2025-04-03 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_company_remove_sucursal_empresa_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='tax_id',
            new_name='cuit',
        ),
    ]
