# Generated by Django 4.2.20 on 2025-04-13 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_control', '0001_initial'),
        ('control', '0004_remove_user_branch_remove_user_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_control.users'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
