# Generated by Django 4.2.20 on 2025-04-25 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0005_alter_stockmovement_user_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='total_stock',
        ),
    ]
