# Generated by Django 4.2.20 on 2025-05-08 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0006_remove_product_total_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
