# Generated by Django 4.2.20 on 2025-08-15 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('control', '0009_alter_company_address_alter_company_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='branch_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='price_at_movement',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='product_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='user_name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='control.branch'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='control.product'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
