# Generated by Django 4.2.20 on 2025-08-15 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0011_backfill_movement_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='branch_name',
            field=models.CharField(default='sin-nombre', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='price_at_movement',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Precio del producto en el momento del movimiento', max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='product_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='user_name',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
